# Generated by Django 6.1 on 2026-08-18 03:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WellnessTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('tip_text', models.TextField()),
                ('category', models.CharField(choices=[('HYDRATION', 'Hydration'), ('POSTURE', 'Posture & Ergonomics'), ('EYES', 'Eye Health (20-20-20)'), ('MOVEMENT', 'Movement & Stretch'), ('BREATH', 'Mindfulness & Breathing')], default='HYDRATION', max_length=20)),
                ('action_label', models.CharField(default='Got it!', max_length=50)),
                ('icon', models.CharField(default='bi-droplet', help_text='Bootstrap Icon class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HydrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('glasses', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hydration_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Vitamin D3, Metformin, Amoxicillin', max_length=200)),
                ('dosage', models.CharField(help_text='e.g. 500mg, 1 tablet, 10ml', max_length=100)),
                ('frequency', models.CharField(choices=[('ONCE', 'Once daily'), ('TWICE', 'Twice daily'), ('THRICE', 'Thrice daily'), ('CUSTOM', 'Custom times')], default='ONCE', max_length=20)),
                ('scheduled_times', models.JSONField(default=list, help_text='List of scheduled times in HH:MM format')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if ongoing', null=True)),
                ('notes', models.CharField(blank=True, default='', help_text='e.g. After meals, with full glass of water', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(default=django.utils.timezone.now)),
                ('scheduled_time', models.CharField(help_text='HH:MM string of scheduled dose', max_length=10)),
                ('status', models.CharField(choices=[('TAKEN', 'Taken'), ('SKIPPED', 'Skipped'), ('SNOOZED', 'Snoozed')], default='TAKEN', max_length=10)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='health.medicine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_date', '-logged_at'],
                'unique_together': {('medicine', 'scheduled_date', 'scheduled_time')},
            },
        ),
    ]
