# Generated by Django 6.1 on 2026-08-18 03:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Task title', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed description (optional)')),
                ('category', models.CharField(choices=[('Work', 'Work'), ('Personal', 'Personal'), ('Health', 'Health'), ('Study', 'Study'), ('Finance', 'Finance'), ('Other', 'Other')], default='Work', max_length=50)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('due_date', models.DateField(default=django.utils.timezone.now, help_text='Due date (defaults to today)')),
                ('due_time', models.TimeField(blank=True, help_text='Due time (optional)', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20)),
                ('recurrence', models.CharField(choices=[('NONE', 'None'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='NONE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', 'due_date', 'due_time', '-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='tasks_task_user_id_c0fce1_idx'), models.Index(fields=['user', 'due_date'], name='tasks_task_user_id_075050_idx'), models.Index(fields=['user', 'priority'], name='tasks_task_user_id_13ec9e_idx')],
            },
        ),
    ]
