# Generated by Django 6.1 on 2026-08-18 03:28

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_hours_start', models.TimeField(default=datetime.time(9, 0), help_text='Start of active work hours (e.g. 09:00)')),
                ('active_hours_end', models.TimeField(default=datetime.time(18, 0), help_text='End of active work hours (e.g. 18:00)')),
                ('hydration_interval_minutes', models.PositiveIntegerField(default=120, help_text='Interval between water nudges in minutes (default 2 hours)')),
                ('water_daily_target', models.PositiveIntegerField(default=8, help_text='Daily water goal in glasses')),
                ('water_intake_today', models.PositiveIntegerField(default=0, help_text='Glasses of water logged today')),
                ('last_water_logged_at', models.DateTimeField(blank=True, null=True)),
                ('last_hydration_nudge_at', models.DateTimeField(blank=True, null=True)),
                ('last_water_reset_date', models.DateField(default=django.utils.timezone.now)),
                ('last_tip_index', models.PositiveIntegerField(default=0)),
                ('reminder_window_minutes', models.PositiveIntegerField(default=30, help_text='Default minutes before task due time to send gentle reminder')),
                ('sound_alerts_enabled', models.BooleanField(default=True, help_text='Play audible chime/alarm for urgent reminders')),
                ('push_subscription', models.JSONField(blank=True, help_text='Browser Web Push subscription payload', null=True)),
                ('onboarding_completed', models.BooleanField(default=False, help_text='Whether user has completed the 3-step walkthrough')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
