# Generated by Django 6.1 on 2026-08-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(choices=[('SEDENTARY', 'Sedentary / Desk Work (Busy Office/Coding)'), ('MODERATE', 'Moderate (Light Exercise / Walking)'), ('HIGH', 'High Activity (Heavy Physical Work / Sports)')], default='SEDENTARY', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(default=28, help_text='Age in years (used for WHO hydration & health guidelines)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other / Prefer not to say')], default='M', max_length=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight_kg',
            field=models.FloatField(default=68.0, help_text='Weight in kilograms'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hydration_interval_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Interval between water nudges in minutes'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='reminder_window_minutes',
            field=models.PositiveIntegerField(default=5, help_text='Minutes before task deadline to trigger alarm reminder'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sound_alerts_enabled',
            field=models.BooleanField(default=True, help_text='Play audible alarm chimes for tasks and health/medications'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='water_daily_target',
            field=models.PositiveIntegerField(default=10, help_text='Daily water goal in glasses (250ml per glass)'),
        ),
    ]
