# Generated by Django 6.1 on 2026-08-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_activity_level_userprofile_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='reminder_window_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Minutes before task deadline to send gentle advance notice (Urgent alarm fires automatically at 5 minutes)'),
        ),
    ]
