# Generated by Django 6.1 on 2026-08-18 03:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('TASK', 'Task Deadline'), ('MEDICINE', 'Medication Dose'), ('HYDRATION', 'Hydration Nudge'), ('WELLNESS', 'Wellness Break')], max_length=20)),
                ('reference_id', models.PositiveIntegerField(blank=True, help_text='Task ID or Medicine ID', null=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('stage', models.CharField(choices=[('GENTLE', 'Gentle Reminder'), ('URGENT', 'Urgent Alert'), ('OVERDUE', 'Overdue Notice')], default='GENTLE', max_length=20)),
                ('scheduled_for', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Delivery'), ('DELIVERED', 'Delivered'), ('DISMISSED', 'Dismissed'), ('SNOOZED', 'Snoozed'), ('ACTIONED', 'Actioned / Done')], default='PENDING', max_length=20)),
                ('snooze_until', models.DateTimeField(blank=True, null=True)),
                ('is_alarm_urgent', models.BooleanField(default=False, help_text='Triggers audible chime / loud alert in browser')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='reminders_r_user_id_449034_idx'), models.Index(fields=['reminder_type', 'reference_id'], name='reminders_r_reminde_9844b5_idx')],
            },
        ),
    ]
